### Register a new user

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name" : "Test User",
    "email" : "test@devflow.com",
    "password" : "password123"
}

### Login

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email" : "test@devflow.com",
    "password" : "password123"
}

# Access Token (Login) - eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxNzE5ODkxLCJleHAiOjE3ODE3MjA3OTF9.1YIVX19HERrU_NZwTEdpKrs14Oo7hA90olAhg701y8Xa3LR0_g0hEQotK6biATXe

### Test protected route (no token - should return 401) 

GET http://localhost:8080/api/v1/test


### Create a project 

POST http://localhost:8080/api/v1/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTM4NjE0LCJleHAiOjE3ODE5Mzk1MTR9.B_Xq9WUf1jQfQdwxA0ARogQsa8VPXbHae7w-7ocSI5BsCeiVhPPbj2FF6lgvCARW

# HTTP/1.1 201 
# X-Content-Type-Options: nosniff
# X-XSS-Protection: 0
# Cache-Control: no-cache, no-store, max-age=0, must-revalidate
# Pragma: no-cache
# Expires: 0
# X-Frame-Options: DENY
# Content-Type: application/json
# Transfer-Encoding: chunked
# Date: Wed, 17 Jun 2026 18:52:11 GMT
# Connection: close

# {
#   "id": 1,
#   "name": "Devflow Backend",
#   "description": "Main backend project for DevFlow app",
#   "isPublic": false,
#   "ownerName": "Test User",
#   "ownerEmail": "test@devflow.com",
#   "createdAt": "2026-06-17T18:52:11.412226200Z"
# }

{
    "name" : "Devflow Backend",
    "description" : "Main backend project for DevFlow app",
    "isPublic" : false
}

### Get my projects

# GET http://localhost:8080/api/v1/projects
# Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxNzIyMjc3LCJleHAiOjE3ODE3MjMxNzd9.VfptyuDhuK2I8rmQflfLNcRFnQyg_IC6hoXC2Dd5TstXfSaEQrQ3Elij90fLWoHd

### Get single project (use id from create response) 
# GET http://localhost:8080/api/v1/projects/1
# Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxNzIyMjc3LCJleHAiOjE3ODE3MjMxNzd9.VfptyuDhuK2I8rmQflfLNcRFnQyg_IC6hoXC2Dd5TstXfSaEQrQ3Elij90fLWoHd

### Update Project

# PUT http://localhost:8080/api/v1/projects/1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxNzIyMjc3LCJleHAiOjE3ODE3MjMxNzd9.VfptyuDhuK2I8rmQflfLNcRFnQyg_IC6hoXC2Dd5TstXfSaEQrQ3Elij90fLWoHd

# {
#     "name" : "DevFlow Backend v2",
#     "description" : "Updated description"
# }

# ### Delete project

# DELETE http://localhost:8080/api/v1/projects/1
# Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxNzIyMjc3LCJleHAiOjE3ODE3MjMxNzd9.VfptyuDhuK2I8rmQflfLNcRFnQyg_IC6hoXC2Dd5TstXfSaEQrQ3Elij90fLWoHd



### Create task
POST http://localhost:8080/api/v1/projects/2/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTM4NjE0LCJleHAiOjE3ODE5Mzk1MTR9.B_Xq9WUf1jQfQdwxA0ARogQsa8VPXbHae7w-7ocSI5BsCeiVhPPbj2FF6lgvCARW

{
    "title" : "Set up CI/CD pipeline",
    "description" : "Configure GitHub Actions for automated testing",
    "priority" : "HIGH",
    "dueDate" : "2026-07-01"
}


### Get tasks for project
GET http://localhost:8080/api/v1/projects/2/tasks
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTM5NjY0LCJleHAiOjE3ODE5NDA1NjR9.xB10Xv9loq0RsjgnfE_Qv2j7qJq-T52zpcEWtjQOoJaYy6m95P2yqzQBOwFzHM6w

### Get single task
GET http://localhost:8080/api/v1/tasks/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTM5NjY0LCJleHAiOjE3ODE5NDA1NjR9.xB10Xv9loq0RsjgnfE_Qv2j7qJq-T52zpcEWtjQOoJaYy6m95P2yqzQBOwFzHM6w

### Update task
PATCH http://localhost:8080/api/v1/tasks/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTM5NjY0LCJleHAiOjE3ODE5NDA1NjR9.xB10Xv9loq0RsjgnfE_Qv2j7qJq-T52zpcEWtjQOoJaYy6m95P2yqzQBOwFzHM6w

{
    "title" : "Set up CI/CD pipeline - UPDATED"
}

### Update status 
PATCH http://localhost:8080/api/v1/tasks/1/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTQwMzEyLCJleHAiOjE3ODE5NDEyMTJ9.Hx2UnRIG52SkRLFPBWVKDri7xsZOKUQL61bAinQwuKVLexh8LzVL6SDYVow2V9el

{
    "status" : "IN_PROGRESS"
}

### Delete task (soft delete)

DELETE http://localhost:8080/api/v1/tasks/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTQwMzEyLCJleHAiOjE3ODE5NDEyMTJ9.Hx2UnRIG52SkRLFPBWVKDri7xsZOKUQL61bAinQwuKVLexh8LzVL6SDYVow2V9el


### Get my projects - first call (cache miss, hits DB) 
GET http://localhost:8080/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyMzIyNTU0LCJleHAiOjE3ODIzMjM0NTR9.aFbUN63gGv43mp5__DMzD6yDAfSyoK3yG185SEvALFPZ4Gz0OvERCZ84sultDwMM

### Get my projects - second call (should be cache hit) 
GET http://localhost:8080/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyMzIyNTU0LCJleHAiOjE3ODIzMjM0NTR9.aFbUN63gGv43mp5__DMzD6yDAfSyoK3yG185SEvALFPZ4Gz0OvERCZ84sultDwMM


### Create project (should evict cache) 
POST http://localhost:8080/api/v1/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyMzc5NjAzLCJleHAiOjE3ODIzODA1MDN9.JyuF3StzV-lw23Rrm0rfwTk_Xh_8rkEJ8VzS037AYecLnxql-u0TmhoGo-RISTKA

{
    "name": "New Test Project",
    "description": "Testing cache eviction",
    "isPublic": true
}


### Get projects (should show new project + hit DB again) 
GET http://localhost:8080/api/v1/projects/2/tasks
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyMzgwNjMyLCJleHAiOjE3ODIzODE1MzJ9.R3eONqaHqh74KJ1KIE7hw4EuR39G4fTNsUH_uahsVEVXN1v4wZ5isugqrjPLU1Bv


### Create task - send this 11 times rapidly
POST http://localhost:8080/api/v1/projects/2/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyNDExMDQyLCJleHAiOjE3ODI0MTE5NDJ9.uy1u0aHtnz3NceeBTZ5oCrRByRRRr5ilx9hD0SrXVKcH8Dha_SXZxZw7PlI7YH1j

{
    "title" : "Rate limit test task",
    "description" : "Testing rate limiting", 
    "priority" : "LOW"
}

### Get current task
GET http://localhost:8080/api/v1/tasks/2
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyNDExMDQyLCJleHAiOjE3ODI0MTE5NDJ9.uy1u0aHtnz3NceeBTZ5oCrRByRRRr5ilx9hD0SrXVKcH8Dha_SXZxZw7PlI7YH1j


### Update task - first user

GET  http://localhost:8080/api/v1/tasks/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyNDEyMDI5LCJleHAiOjE3ODI0MTI5Mjl9.Ky1MU8nzeTfjuW35ph0h7TuIK_H2cOcc3n-9hYdDvwAaDL5x-HVqbrcMixQ_XOAy

{
    "title" : "First user update"
}

### Update task - second user (concurrent)
GET  http://localhost:8080/api/v1/tasks/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyNDEyMDI5LCJleHAiOjE3ODI0MTI5Mjl9.Ky1MU8nzeTfjuW35ph0h7TuIK_H2cOcc3n-9hYdDvwAaDL5x-HVqbrcMixQ_XOAy

{
    "title" : "Second user update"
}

### Get tasks with pagination 

GET http://localhost:8080/api/v1/projects/2/tasks?page=0&size=5
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyNDQ2OTY3LCJleHAiOjE3ODI0NDc4Njd9.nNEE8LA-eqFFvk3NX0UT6FGdE0vKkj1mQQWAzlQgBpMqnosmHYsqVlg5LkdFBk4Y

### Get tasks filtered by status
GET http://localhost:8080/api/v1/projects/2/tasks?status+TODO&page=0&size=5
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyNDQ2OTY3LCJleHAiOjE3ODI0NDc4Njd9.nNEE8LA-eqFFvk3NX0UT6FGdE0vKkj1mQQWAzlQgBpMqnosmHYsqVlg5LkdFBk4Y

### Page 2 

GET http://localhost:8080/api/v1/projects/2/tasks?page=1&size=5
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyNDUxNzQ0LCJleHAiOjE3ODI0NTI2NDR9.vWubb-_8vvruTy1S-3YeRT-1cuhkYQ5BoHdFooHlljp-2KSV-KrsydUeacEvo0qq


### Filter by status 
GET http://localhost:8080/api/v1/projects/2/tasks?status+TODO&page=0&size=5
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyNDUxNzQ0LCJleHAiOjE3ODI0NTI2NDR9.vWubb-_8vvruTy1S-3YeRT-1cuhkYQ5BoHdFooHlljp-2KSV-KrsydUeacEvo0qq


### Create label
POST http://localhost:8080/api/v1/projects/2/labels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyODc4OTcxLCJleHAiOjE3ODI4Nzk4NzF9.jvsTobm1_sGaz_7mhm922M9eF8WI4E1ZLfWvznIeF5BvRRjjXxYHvVjCndB2lH9E

{
    "name" : "bug",
    "color" : "#FF5733"
}

### Create another label
POST http://localhost:8080/api/v1/projects/2/labels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyODc4OTcxLCJleHAiOjE3ODI4Nzk4NzF9.jvsTobm1_sGaz_7mhm922M9eF8WI4E1ZLfWvznIeF5BvRRjjXxYHvVjCndB2lH9E

{
    "name" : "feature",
    "color" : "#33FF57"
}

### List labels for project
GET http://localhost:8080/api/v1/tasks/2
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyODk5OTc4LCJleHAiOjE3ODI5MDA4Nzh9.r6VOYsXS7UDqH5OiNkLej1DLSeKQByb6fMuEktRwCsHsH3Cg8NSlnfjg-v6GM-X6
### Attach label to task (use label id from response above)
POST http://localhost:8080/api/v1/tasks/2/labels/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyODk5OTc4LCJleHAiOjE3ODI5MDA4Nzh9.r6VOYsXS7UDqH5OiNkLej1DLSeKQByb6fMuEktRwCsHsH3Cg8NSlnfjg-v6GM-X6

### Remove label from task
DELETE http://localhost:8080/api/v1/tasks/2/labels/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyODc5MzUzLCJleHAiOjE3ODI4ODAyNTN9.aFXmiRjvE53DdDALR_9wWEly3pasX_iYm0zfwtT8De2HKTrVe7ZVPnIqghBpTOUh


### Change task status (this should log an activity)

PATCH http://localhost:8080/api/v1/tasks/2/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgzMDU1NzEwLCJleHAiOjE3ODMwNTY2MTB9.a1-AAOuxwwR-4MFDPdGituNxD8Ve8MkRykRq9vsAh2Xf_YCu5VALIUcuXCHznPya

{
    "status" : "IN_PROGRESS"
}

### Change it again

PATCH http://localhost:8080/api/v1/tasks/2/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgzMDU1NzEwLCJleHAiOjE3ODMwNTY2MTB9.a1-AAOuxwwR-4MFDPdGituNxD8Ve8MkRykRq9vsAh2Xf_YCu5VALIUcuXCHznPya

{
    "status" : "IN_REVIEW"
}

### Get Activity Log

GET http://localhost:8080/api/v1/tasks/2/activity
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgzMDU1NzEwLCJleHAiOjE3ODMwNTY2MTB9.a1-AAOuxwwR-4MFDPdGituNxD8Ve8MkRykRq9vsAh2Xf_YCu5VALIUcuXCHznPya


### Register second user 
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name" : "Member User",
    "email" : "member@devflow.com",
    "password" : "password123"
}

### Login as owner (test@devflow.com)
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email" : "test@devflow.com",
    "password" : "password123"
}

### Invite member
POST http://localhost:8080/api/v1/projects/2/members
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgzODY3ODYwLCJleHAiOjE3ODM4Njg3NjB9.GgBbIq9ttVC3jfRZGgMDZzpEb35YcS_NspNxoRb2LHzcEhgn4Yl5dzxCnxL_rwgT

{
    "email" : "member@devflow.com"
}

### List members

GET http://localhost:8080/api/v1/projects/2/members
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgzODY3ODYwLCJleHAiOjE3ODM4Njg3NjB9.GgBbIq9ttVC3jfRZGgMDZzpEb35YcS_NspNxoRb2LHzcEhgn4Yl5dzxCnxL_rwgT

### Remove member

DELETE http://localhost:8080/api/v1/projects/2/members/2
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgzODY3ODYwLCJleHAiOjE3ODM4Njg3NjB9.GgBbIq9ttVC3jfRZGgMDZzpEb35YcS_NspNxoRb2LHzcEhgn4Yl5dzxCnxL_rwgT
