### Register a new user

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name" : "Test User",
    "email" : "test@devflow.com",
    "password" : "password123"
}

### Login

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email" : "test@devflow.com",
    "password" : "password123"
}

# Access Token (Login) - eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxNzE5ODkxLCJleHAiOjE3ODE3MjA3OTF9.1YIVX19HERrU_NZwTEdpKrs14Oo7hA90olAhg701y8Xa3LR0_g0hEQotK6biATXe

### Test protected route (no token - should return 401) 

GET http://localhost:8080/api/v1/test


### Create a project 

POST http://localhost:8080/api/v1/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTM4NjE0LCJleHAiOjE3ODE5Mzk1MTR9.B_Xq9WUf1jQfQdwxA0ARogQsa8VPXbHae7w-7ocSI5BsCeiVhPPbj2FF6lgvCARW

# HTTP/1.1 201 
# X-Content-Type-Options: nosniff
# X-XSS-Protection: 0
# Cache-Control: no-cache, no-store, max-age=0, must-revalidate
# Pragma: no-cache
# Expires: 0
# X-Frame-Options: DENY
# Content-Type: application/json
# Transfer-Encoding: chunked
# Date: Wed, 17 Jun 2026 18:52:11 GMT
# Connection: close

# {
#   "id": 1,
#   "name": "Devflow Backend",
#   "description": "Main backend project for DevFlow app",
#   "isPublic": false,
#   "ownerName": "Test User",
#   "ownerEmail": "test@devflow.com",
#   "createdAt": "2026-06-17T18:52:11.412226200Z"
# }

{
    "name" : "Devflow Backend",
    "description" : "Main backend project for DevFlow app",
    "isPublic" : false
}

### Get my projects

# GET http://localhost:8080/api/v1/projects
# Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxNzIyMjc3LCJleHAiOjE3ODE3MjMxNzd9.VfptyuDhuK2I8rmQflfLNcRFnQyg_IC6hoXC2Dd5TstXfSaEQrQ3Elij90fLWoHd

### Get single project (use id from create response) 
# GET http://localhost:8080/api/v1/projects/1
# Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxNzIyMjc3LCJleHAiOjE3ODE3MjMxNzd9.VfptyuDhuK2I8rmQflfLNcRFnQyg_IC6hoXC2Dd5TstXfSaEQrQ3Elij90fLWoHd

### Update Project

# PUT http://localhost:8080/api/v1/projects/1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxNzIyMjc3LCJleHAiOjE3ODE3MjMxNzd9.VfptyuDhuK2I8rmQflfLNcRFnQyg_IC6hoXC2Dd5TstXfSaEQrQ3Elij90fLWoHd

# {
#     "name" : "DevFlow Backend v2",
#     "description" : "Updated description"
# }

# ### Delete project

# DELETE http://localhost:8080/api/v1/projects/1
# Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxNzIyMjc3LCJleHAiOjE3ODE3MjMxNzd9.VfptyuDhuK2I8rmQflfLNcRFnQyg_IC6hoXC2Dd5TstXfSaEQrQ3Elij90fLWoHd



### Create task
POST http://localhost:8080/api/v1/projects/2/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTM4NjE0LCJleHAiOjE3ODE5Mzk1MTR9.B_Xq9WUf1jQfQdwxA0ARogQsa8VPXbHae7w-7ocSI5BsCeiVhPPbj2FF6lgvCARW

{
    "title" : "Set up CI/CD pipeline",
    "description" : "Configure GitHub Actions for automated testing",
    "priority" : "HIGH",
    "dueDate" : "2026-07-01"
}


### Get tasks for project
GET http://localhost:8080/api/v1/projects/2/tasks
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTM5NjY0LCJleHAiOjE3ODE5NDA1NjR9.xB10Xv9loq0RsjgnfE_Qv2j7qJq-T52zpcEWtjQOoJaYy6m95P2yqzQBOwFzHM6w

### Get single task
GET http://localhost:8080/api/v1/tasks/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTM5NjY0LCJleHAiOjE3ODE5NDA1NjR9.xB10Xv9loq0RsjgnfE_Qv2j7qJq-T52zpcEWtjQOoJaYy6m95P2yqzQBOwFzHM6w

### Update task
PATCH http://localhost:8080/api/v1/tasks/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTM5NjY0LCJleHAiOjE3ODE5NDA1NjR9.xB10Xv9loq0RsjgnfE_Qv2j7qJq-T52zpcEWtjQOoJaYy6m95P2yqzQBOwFzHM6w

{
    "title" : "Set up CI/CD pipeline - UPDATED"
}

### Update status 
PATCH http://localhost:8080/api/v1/tasks/1/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTQwMzEyLCJleHAiOjE3ODE5NDEyMTJ9.Hx2UnRIG52SkRLFPBWVKDri7xsZOKUQL61bAinQwuKVLexh8LzVL6SDYVow2V9el

{
    "status" : "IN_PROGRESS"
}

### Delete task (soft delete)

DELETE http://localhost:8080/api/v1/tasks/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgxOTQwMzEyLCJleHAiOjE3ODE5NDEyMTJ9.Hx2UnRIG52SkRLFPBWVKDri7xsZOKUQL61bAinQwuKVLexh8LzVL6SDYVow2V9el


### Get my projects - first call (cache miss, hits DB) 
GET http://localhost:8080/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyMzIyNTU0LCJleHAiOjE3ODIzMjM0NTR9.aFbUN63gGv43mp5__DMzD6yDAfSyoK3yG185SEvALFPZ4Gz0OvERCZ84sultDwMM

### Get my projects - second call (should be cache hit) 
GET http://localhost:8080/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyMzIyNTU0LCJleHAiOjE3ODIzMjM0NTR9.aFbUN63gGv43mp5__DMzD6yDAfSyoK3yG185SEvALFPZ4Gz0OvERCZ84sultDwMM


### Create project (should evict cache) 
POST http://localhost:8080/api/v1/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyMzc5NjAzLCJleHAiOjE3ODIzODA1MDN9.JyuF3StzV-lw23Rrm0rfwTk_Xh_8rkEJ8VzS037AYecLnxql-u0TmhoGo-RISTKA

{
    "name": "New Test Project",
    "description": "Testing cache eviction",
    "isPublic": true
}


### Get projects (should show new project + hit DB again) 
GET http://localhost:8080/api/v1/projects
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ0ZXN0QGRldmZsb3cuY29tIiwiaWF0IjoxNzgyMzc5NjAzLCJleHAiOjE3ODIzODA1MDN9.JyuF3StzV-lw23Rrm0rfwTk_Xh_8rkEJ8VzS037AYecLnxql-u0TmhoGo-RISTKA